export const rutas = {
  inicio: '/',
  login: '/login',
  panel: '/panel',
  equipos: '/equipos',
  partidos: '/partidos',
  brackets: '/brackets',
  bracketCompleto: '/bracket/:subcategoriaId',
  homologacion: '/homologacion',
  juez: '/juez',
  juezPartido: '/juez/:id',
  llave: '/llave',
  llaveSubcategoria: '/llave/:subcategoriaId',
  sorteo: '/sorteo',
}
